CREATE TABLE "users" (
  "user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(50) UNIQUE NOT NULL,
  "email" varchar(100) UNIQUE NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "role" varchar(20) DEFAULT 'customer',
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "user_preferences" (
  "preference_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int UNIQUE NOT NULL,
  "max_budget" decimal(6,2) DEFAULT 50,
  "max_distance_km" decimal(4,2) DEFAULT 10,
  "updated_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "restaurant_users" (
  "restaurant_user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "restaurant_id" int NOT NULL,
  "username" varchar(50) UNIQUE NOT NULL,
  "email" varchar(100) UNIQUE NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "role" varchar(20) DEFAULT 'manager',
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "restaurants" (
  "restaurant_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "address" text NOT NULL,
  "latitude" decimal(9,6) NOT NULL,
  "longitude" decimal(9,6) NOT NULL,
  "rating" decimal(3,2) DEFAULT 0,
  "is_active" boolean DEFAULT true
);

CREATE TABLE "food_items" (
  "food_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "restaurant_id" int NOT NULL,
  "name" varchar(100) NOT NULL,
  "description" text,
  "image_url" varchar(255) NOT NULL,
  "price" decimal(6,2) NOT NULL,
  "is_available" boolean DEFAULT true
);

CREATE TABLE "tags" (
  "tag_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tag_name" varchar(50) UNIQUE NOT NULL,
  "tag_type" varchar(20) NOT NULL
);

CREATE TABLE "food_tags" (
  "food_id" int NOT NULL,
  "tag_id" int NOT NULL,
  PRIMARY KEY ("food_id", "tag_id")
);

CREATE TABLE "swipe_logs" (
  "swipe_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "food_id" int NOT NULL,
  "action" varchar(20) NOT NULL,
  "swiped_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "cart_items" (
  "cart_item_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "food_id" int NOT NULL,
  "quantity" int NOT NULL DEFAULT 1,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "promotions" (
  "promo_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "restaurant_id" int,
  "promo_code" varchar(20) UNIQUE NOT NULL,
  "discount_type" varchar(20) NOT NULL,
  "discount_value" decimal(6,2) NOT NULL,
  "min_order_value" decimal(6,2) DEFAULT 0,
  "start_date" timestamp NOT NULL,
  "end_date" timestamp NOT NULL,
  "is_active" boolean DEFAULT true
);

CREATE TABLE "user_coupons" (
  "user_id" int NOT NULL,
  "promo_id" int NOT NULL,
  "used_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  PRIMARY KEY ("user_id", "promo_id")
);

CREATE TABLE "orders" (
  "order_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "restaurant_id" int NOT NULL,
  "promo_id" int,
  "delivery_address" text NOT NULL,
  "subtotal" decimal(8,2) NOT NULL,
  "discount_amount" decimal(6,2) DEFAULT 0,
  "delivery_fee" decimal(5,2) NOT NULL,
  "total_price" decimal(8,2) NOT NULL,
  "order_status" varchar(20) DEFAULT 'pending',
  "ordered_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "order_items" (
  "order_item_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" int NOT NULL,
  "food_id" int,
  "quantity" int NOT NULL,
  "price_at_purchase" decimal(6,2) NOT NULL
);

COMMENT ON COLUMN "restaurant_users"."role" IS 'Values: owner, manager, staff';

COMMENT ON COLUMN "tags"."tag_type" IS 'Values: category, cuisine, flavor';

COMMENT ON COLUMN "swipe_logs"."action" IS 'Values: pass, love, favorite';

COMMENT ON COLUMN "promotions"."restaurant_id" IS 'If null, it is a system-wide discount. If populated, it is restaurant-specific.';

COMMENT ON COLUMN "promotions"."discount_type" IS 'Values: percentage, fixed_amount, free_delivery';

COMMENT ON COLUMN "orders"."order_status" IS 'Values: pending, preparing, ready_for_pickup, delivering, completed, cancelled';

ALTER TABLE "user_preferences" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "restaurant_users" ADD FOREIGN KEY ("restaurant_id") REFERENCES "restaurants" ("restaurant_id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "swipe_logs" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "swipe_logs" ADD FOREIGN KEY ("food_id") REFERENCES "food_items" ("food_id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "food_items" ADD FOREIGN KEY ("restaurant_id") REFERENCES "restaurants" ("restaurant_id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "food_tags" ADD FOREIGN KEY ("food_id") REFERENCES "food_items" ("food_id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "food_tags" ADD FOREIGN KEY ("tag_id") REFERENCES "tags" ("tag_id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cart_items" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cart_items" ADD FOREIGN KEY ("food_id") REFERENCES "food_items" ("food_id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_coupons" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_coupons" ADD FOREIGN KEY ("promo_id") REFERENCES "promotions" ("promo_id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "promotions" ADD FOREIGN KEY ("restaurant_id") REFERENCES "restaurants" ("restaurant_id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "orders" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "orders" ADD FOREIGN KEY ("restaurant_id") REFERENCES "restaurants" ("restaurant_id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "orders" ADD FOREIGN KEY ("promo_id") REFERENCES "promotions" ("promo_id") ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_items" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("order_id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_items" ADD FOREIGN KEY ("food_id") REFERENCES "food_items" ("food_id") ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

CREATE TABLE "page_analytics" (
  "analytics_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "page_path" varchar(255) NOT NULL,
  "visitor_id" varchar(255) NOT NULL,
  "timestamp" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

-- index to improve performance

CREATE INDEX IF NOT EXISTS idx_swipe_logs_user_id_swiped_at ON swipe_logs (user_id, swiped_at DESC);
CREATE INDEX IF NOT EXISTS idx_swipe_logs_food_id ON swipe_logs (food_id);

CREATE INDEX IF NOT EXISTS idx_food_items_restaurant_id ON food_items (restaurant_id);
CREATE INDEX IF NOT EXISTS idx_food_items_is_available_price ON food_items (is_available, price);

CREATE INDEX IF NOT EXISTS idx_restaurants_lat_lng ON restaurants (latitude, longitude);

CREATE INDEX IF NOT EXISTS idx_cart_items_user_id ON cart_items (user_id);

CREATE INDEX IF NOT EXISTS idx_orders_user_id_ordered_at ON orders (user_id, ordered_at DESC);
CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON order_items (order_id);

CREATE INDEX IF NOT EXISTS idx_promotions_restaurant_id_active ON promotions (restaurant_id, is_active);

CREATE INDEX IF NOT EXISTS idx_tags_tag_type ON tags (tag_type);

CREATE INDEX IF NOT EXISTS idx_page_analytics_timestamp ON page_analytics (timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_page_analytics_visitor_id ON page_analytics (visitor_id);
CREATE INDEX IF NOT EXISTS idx_page_analytics_page_path ON page_analytics (page_path);

